name: singan
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2020.6.20
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.1.1
  - python=3.6.10
  - readline=7.0
  - setuptools=47.3.1
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - decorator==4.4.2
    - future==0.18.2
    - imageio==2.8.0
    - joblib==0.15.1
    - kiwisolver==1.2.0
    - matplotlib==3.2.2
    - networkx==2.4
    - numpy==1.19.0
    - pillow==7.1.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - scikit-learn==0.23.1
    - scipy==1.5.0
    - six==1.15.0
    - threadpoolctl==2.1.0
    - tifffile==2020.6.3
    - torch==1.4.0
    - torchvision==0.5.0
